export class vendorsDB  {
    static data = [
        {
            vendor : "<img src='assets/images/team/3.jpg' class='imgTable'> <span>Anna sanches</span>",
            products : "985474589",
            store_name: "ALICORP",
            date:"8/10/18",
            balance:"s/ 576",
            revenue:"s/ 9761266",
        },
        {
            vendor : "<img src='assets/images/dashboard/designer.jpg' class='imgTable'> <span>Carlos santana</span>",
            products : "978541125",
            store_name: "GRUPO GLORIA",
            date:"6/5/18",
            balance:"s/ 780",
            revenue:"s/ 8793611",
        },
        {
            vendor : "<img src='assets/images/dashboard/boy-2.png' class='imgTable'> <span>Fermando Paredes</span>",
            products : "985478521",
            store_name: "PEPSICOLA",
            date:"25/2/18",
            balance:"s/ 245",
            revenue:"s/ 1279520",
        },
        {
            vendor : "<img src='assets/images/dashboard/user.png' class='imgTable'> <span>Laidy Meza</span>",
            products : "963258741",
            store_name: "AJEPER",
            date:"30/3/18",
            balance:"s/ 781",
            revenue:"s/ 8761424",
        },
        {
            vendor : "<img src='assets/images/dashboard/user1.jpg' class='imgTable'> <span>Juan Amao</span>",
            products : "965214523",
            store_name: "NESTLÉ",
            date:"4/8/18",
            balance:"s/ 899",
            revenue:"s/ 10285255",
        },
        {
            vendor : "<img src='assets/images/team/1.jpg' class='imgTable'> <span>Samuel Eto</span>",
            products : "985412541",
            store_name: "ALI",
            date:"11/7/18",
            balance:"s/ 876",
            revenue:"s/ 947611",
        },
        {
            vendor : "<img src='assets/images/dashboard/user3.jpg' class='imgTable'> <span>Andres Peres</span>",
            products : "921452145",
            store_name: "Betatech",
            date:"17/9/18",
            balance:"s/ 324",
            revenue:"s/ 647212",
        },
        {
            vendor : "<img src='assets/images/team/2.jpg' class='imgTable'> <span>Camilo paredes</span>",
            products : "963254125",
            store_name: "Warephase",
            date:"8/10/18",
            balance:"s/ 5761",
            revenue:"s/ 9761266",
        },
        {
            vendor : "<img src='assets/images/dashboard/user5.jpg' class='imgTable'> <span>Salomon Santana</span>",
            products : "965874125",
            store_name: "Sunnamplex",
            date:"5/6/18",
            balance:"s/ 876",
            revenue:"s/631479",
        },
        {
            vendor : "<img src='assets/images/dashboard/user2.jpg' class='imgTable'> <span>Andres hurtado</span>",
            products : "965214785 ",
            store_name: "Kan-code",
            date:"15/4/18",
            balance:"s/ 279",
            revenue:"s/ 579214",
        },
    ]
}